name = "CJKFrequencies"
uuid = "3a858bc7-ae0d-44ab-8a92-ee3192d2dedf"
authors = ["Timothy Lin <32549553+tmthyln@users.noreply.github.com>"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
LightXML = "9c8b4983-aa76-5018-a973-4c85ecc9e179"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
DataStructures = "0.18"
LightXML = "0.9"
julia = "1.3"
